# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Checking node and npm version
        run: |
          node -v
          npm -v
      # - name: Creating folder for Backup
      #   run: mkdir db_backup
      - name: Installing Packages
        run: |
          npm install
      - name: Starting the Node File
        run: node index
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_NAME: ${{secrets.DB_NAME}}
          ALL_DB: ${{secrets.ALL_DATABASE}}
          WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
      - name: Commiting to the Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated Database Backups"
          git push
